//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Library.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group.
        /// </summary>
        internal static string Group_LowCase {
            get {
                return ResourceManager.GetString("Group_LowCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;groups&gt;
        ///    &lt;group name=&quot;1&quot;&gt;
        ///        &lt;item name=&quot;1&quot;/&gt;
        ///        &lt;item name=&quot;2&quot;/&gt;
        ///        &lt;item name=&quot;11&quot;/&gt;
        ///        &lt;item name=&quot;22&quot;/&gt;
        ///        &lt;item name=&quot;33&quot;/&gt;
        ///        &lt;item name=&quot;444&quot;/&gt;
        ///    &lt;/group&gt;
        ///    &lt;group name=&quot;2&quot;&gt;
        ///        &lt;item name=&quot;3&quot;/&gt;
        ///        &lt;item name=&quot;4&quot;/&gt;
        ///        &lt;item name=&quot;111&quot;/&gt;
        ///        &lt;item name=&quot;222&quot;/&gt;
        ///        &lt;item name=&quot;333&quot;/&gt;
        ///        &lt;item name=&quot;555&quot;/&gt;
        ///    &lt;/group&gt;
        ///    &lt;group name=&quot;3&quot;&gt;
        ///        &lt;item name=&quot;5&quot;/&gt;
        ///        &lt;item nam [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to groups.
        /// </summary>
        internal static string Groups_LowCase {
            get {
                return ResourceManager.GetString("Groups_LowCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to item.
        /// </summary>
        internal static string Item_LowCase {
            get {
                return ResourceManager.GetString("Item_LowCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to itemsCount.
        /// </summary>
        internal static string ItemsCount_LowCase {
            get {
                return ResourceManager.GetString("ItemsCount_LowCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;list itemsCount=&quot;15&quot;&gt;
        ///  &lt;item name=&quot;1&quot; group=&quot;1&quot; /&gt;
        ///  &lt;item name=&quot;2&quot; group=&quot;1&quot; /&gt;
        ///  &lt;item name=&quot;5&quot; group=&quot;3&quot; /&gt;
        ///  &lt;item name=&quot;3&quot; group=&quot;2&quot; /&gt;
        ///  &lt;item name=&quot;4&quot; group=&quot;2&quot; /&gt;
        ///  &lt;item name=&quot;11&quot; group=&quot;1&quot; /&gt;
        ///  &lt;item name=&quot;22&quot; group=&quot;1&quot; /&gt;
        ///  &lt;item name=&quot;33&quot; group=&quot;1&quot; /&gt;
        ///  &lt;item name=&quot;44&quot; group=&quot;3&quot; /&gt;
        ///  &lt;item name=&quot;55&quot; group=&quot;3&quot; /&gt;
        ///  &lt;item name=&quot;111&quot; group=&quot;2&quot; /&gt;
        ///  &lt;item name=&quot;222&quot; group=&quot;2&quot; /&gt;
        ///  &lt;item name=&quot;333&quot; group=&quot;2&quot; /&gt;
        ///  &lt;item name=&quot;444&quot; group=&quot;1&quot; /&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list.
        /// </summary>
        internal static string List_LowCase {
            get {
                return ResourceManager.GetString("List_LowCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to name.
        /// </summary>
        internal static string Name_LowCase {
            get {
                return ResourceManager.GetString("Name_LowCase", resourceCulture);
            }
        }
    }
}
